export const ESTADOS = [
  "En proceso",
  "Detenido",
  "Mantenimiento",
  "Falla",
  "Disponible",
  "Limpieza superficial",
  "Limpieza profunda",
  "Espera de producto",
  "Alistamiento",
  "Investigación y desarrollo",
  "Paro por locativos",
] as const;

export const PRODUCTOS = [
  "N/A",
  "Acetaminofen 100 mg/mL Gotas",
  "Acetaminofen 150 mg/ 5mL Jarabe",
  "Acetaminofen 325 mg + Fosfato de Codeina 30 mg Tabletas",
  "Acetaminofen 500 mg Tabletas",
  "Aciclovir 200 mg Tabletas",
  "Aciclovir 5% Ungüento",
  "Aciclovir 800 mg Tabletas",
  "Acido Folico 1 mg Tabletas",
  "Acido Fusidico 2% Crema",
  "Albendazol 200 mg Tabletas",
  "Albendazol 400 mg/20 mL Suspension",
  "Ambroxol 15 mg/5 mL Jarabe Pediatrico",
  "Ambroxol 30 mg/5 mL Jarabe",
  "Amitriptilina Clorhidrato 25 mg Tabletas Recubiertas",
  "Amlodipino 5 mg Tabletas",
  "Amoxicilina 500 mg Cápsulas",
  "Atorvastatina 20 mg Tabletas Recubiertas",
  "Atorvastatina 40 mg Tabletas Recubiertas",
  "Azitromicina 500 mg Tabletas Recubiertas",
  "Betahistina Diclorhidrato 8 mg Tabletas",
  "Betametasona 0,05% Crema",
  "Betametasona 0,1% Crema",
  "Calcio 600 mg + Vitamina D3 200 U.I Tabletas Masticables",
  "Carbamazepina 200 mg Tabletas",
  "Cetirizina Clorhidrato 10 mg Tabletas Recubiertas",
  "Ciprofloxacina 500 mg Tabletas Recubiertas",
  "Clobetasol Propionato 0.05% Crema",
  "Clonazepam 2,5mg/mL Solución Oral",
  "Clopidogrel 75 mg Tabletas Recubiertas",
  "Clotrimazol 1% + Betametasona 0,04% + Neomicina 0,5% Crema",
  "Clotrimazol 1% Crema",
  "Clotrimazol 1% Crema Vaginal",
  "Clotrimazol 1% Solucion Topica",
  "Colchicina 0,5 mg Tabletas",
  "Complejo B Tabletas Recubiertas",
  "Desloratadina 0,5 mg/mL Jarabe",
  "Desloratadina 5 mg Tabletas Recubiertas",
  "Diclofenaco Sodico 50 mg Tabletas Recubiertas",
  "Difenhidramina Clorhidrato 12,5 mg/5 mL Jarabe",
  "Dinitrato de Isosorbide 10 mg Tabletas",
  "Enerzinc 200 mg/100 mL Solucion Oral",
  "Esomeprazol 20 mg Tabletas con Cubierta Entérica",
  "Esomeprazol 40 mg Tabletas con Cubierta Entérica",
  "Espironolactona 25 mg Tabletas",
  "Fexofenadina Clorhidrato 120 mg Tabletas Recubiertas",
  "Fin-Espam 10 mg Tabletas Recubiertas",
  "Fin-Espam Compuesto Tabletas Recubiertas",
  "Fin-Espam Fem Tabletas Recubiertas",
  "Fluconazol 200 mg Capsulas",
  "Fluoxetina 20 mg Capsulas",
  "Fluoxetina 20 mg Tabletas Recubiertas",
  "Folic Prevent 400 mcg Tabletas",
  "Furosemida 40 mg Tabletas",
  "Gemfibrozilo 600 mg Tabletas Recubiertas",
  "Glibenclamida 5 mg Tabletas",
  "Granulado de Acido Folico para IOFI Tabletas",
  "Guayaproff 300 mg/15 mL Jarabe",
  "Hidroclorotiazida 25 mg Tabletas",
  "Hioscina N-Butil Bromuro 10 mg Tabletas Recubiertas",
  "Ibuprofeno 400 mg Tabletas Recubiertas",
  "Ibuprofeno 800 mg Tabletas Recubiertas",
  "Imipramina Clorhidrato 25 mg Tabletas Recubiertas",
  "IOFI DHA Y EPA Cápsulas",
  "IOFI Tabletas Recubiertas",
  "Ketoconazol 200 mg Tabletas",
  "Ketotifeno 20 mg/100 mL Jarabe",
  "Levetiracetam 1000 mg Tabletas Recubiertas",
  "Levofloxacina 500 mg Tabletas Recubiertas",
  "Loperamida Clorhidrato 2 mg Tabletas",
  "Loratadina 10 mg Tabletas",
  "Loratadina 5 mg/5 mL (0.1%) Jarabe",
  "Lorazepam 2 mg Tabletas",
  "Losartan Potasico 100 mg + Hidroclorotiazida 25 mg Tabletas Recubiertas",
  "Losartan Potasico 100 mg Tabletas Recubiertas",
  "Losartan Potasico 50 mg + Hidroclorotiazida 12,5 mg Tabletas Recubiertas",
  "Losartan Potasico 50 mg Tabletas Recubiertas",
  "Lovastatina 20 mg Tabletas",
  "Memantina Clorhidrato 10 mg Tabletas Recubiertas",
  "Metformina Clorhidrato 500 mg Tabletas Recubiertas",
  "Metocarbamol 750 mg Tabletas Recubiertas",
  "Metoclopramida 10 mg Tabletas",
  "Metoprolol Tartrato 100 mg Tabletas Recubiertas",
  "Metoprolol Tartrato 50 mg Tabletas Recubiertas",
  "Metronidazol 500 mg Tabletas Recubiertas",
  "Minoxidil 5% Solución Tópica",
  "Mometasona Furoato 0,1% Crema",
  "Naproxeno 250 mg Tabletas Recubiertas",
  "Naproxeno 500 mg Tabletas Recubiertas",
  "Nitrofurantoina Macrocristales 100 mg Capsulas",
  "Norfloxacino 400 mg Tabletas Recubiertas",
  "Orocal 1500 mg Tabletas Masticables",
  "Orocal D Tabletas",
  "Prednisolona 5 mg Tabletas",
  "Pregabalina 150 mg Cápsulas",
  "Pregabalina 50 mg Cápsulas",
  "Pregabalina 75 mg Cápsulas",
  "Rosuvastatina 20 mg Tabletas Recubiertas",
  "Rosuvastatina 40 mg Tabletas Recubiertas",
  "Salbutamol 2 mg/5 mL Jarabe",
  "Sanafen 150 mg/5mL Jarabe",
  "Sanafen 500 mg Tabletas",
  "Sildenafilo 50 mg Tabletas Recubiertas",
  "Sulfato Ferroso 125 mg/mL Gotas",
  "Sulfato Ferroso 300 mg Tabletas Recubiertas",
  "Sulfato Ferroso 600 mg/15 mL Jarabe",
  "Suprifeno 100 mg/5 mL Suspension",
  "Tadalafilo 20 mg Tabletas Recubiertas",
  "Tadalafilo 5 mg Tabletas Recubiertas",
  "Tiamina 300 mg Tabletas",
  "Tramadol Clorhidrato 100 mg/mL Solucion Oral (Gotas)",
  "Trimebutina Maleato 200 mg Tabletas",
  "Yodinfex 10% Solucion Topica",
  "Zopiclona 7,5 mg Tabletas Recubiertas",
] as const;

export type Estado = (typeof ESTADOS)[number];
export type Producto = (typeof PRODUCTOS)[number];
